# Generated by Django 3.2.7 on 2021-11-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighborhood'),
        ),
    ]
